CREATE TABLE sagas_subcategories (
  id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  sagaID INTEGER UNSIGNED NOT NULL,
  subcategoryID INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY (sagaID) REFERENCES sagas(id),
  FOREIGN KEY (subcategoryID) REFERENCES subcategories(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
